In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
# Import Dependencies for Database
from config import password
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect
import psycopg2
import pandas as pd

In [3]:
db_string = f"postgresql+psycopg2://postgres:" + password + "@127.0.0.1:5432/the_cheesery"

In [4]:
engine = create_engine(db_string)

In [5]:
inspector = inspect(engine)

In [6]:
inspector.get_table_names()

['cheese']

In [7]:
session = Session(engine)

In [8]:
engine.execute("SELECT * from cheese")

In [9]:
col_names_list = []

#i = 0
for i in range(len(inspector.get_columns('cheese'))):
    col_names_list.append(inspector.get_columns('cheese')[i]['name'])
    
print(col_names_list)

['cheese', 'company', 'city', 'price', 'milk', 'country', 'origin', 'classification', 'texture', 'color', 'flavor', 'vegetarian']

In [10]:
# create a df from database 
cheese_data_df = pd.DataFrame(columns = col_names_list)

In [11]:
# add in data
import sys
db = engine.execute("SELECT * from cheese")
for record in db:
    record_series = pd.Series(list(record), index = cheese_data_df.columns)
    
    cheese_data_df = cheese_data_df.append(record_series, ignore_index=True)

In [12]:
# review df
cheese_data_df

,cheese,company,city,price,milk,country,origin,classification,texture,color,flavor,vegetarian
0,crescenza,mozzarella company,dallas,9.39,cow,italy,italian,fresh soft,creamy,white,sweet,yes
1,smoked scamorza,mozzarella company,dallas,15.59,cow,italy,pasta filata,semi soft,firm,white,smokey,no
2,smoked mozzarella,mozzarella company,dallas,10.79,cow,italy,mozzarella,semi soft,bouncy,white,smokey,yes
3,queso oaxaca,mozzarella company,dallas,11.99,cow,mexico,pasta filata,semi hard,bouncy,white,buttery,yes
4,queso fresco,mozzarella company,dallas,10.79,cow,mexico,cottage,fresh soft,crumbly,white,milky,yes
...,...,...,...,...,...,...,...,...,...,...,...,...
98,feta,brazos valley cheese,waco,15,cow,greece,feta,soft brined,crumbly,white,tangy,no
99,marinated feta,brazos valley cheese,waco,14,cow,greece,feta,soft brined,crumbly,white,herby,no
100,marinated labneh,brazos valley cheese,waco,14,cow,middle east,labneh,soft,creamy,white,herby,no
101,mountain maple brie,brazos valley cheese,waco,22.5,cow,united states,brie,soft,creamy,cream,sweet,no
102,orchard blue,brazos valley cheese,waco,16.5,cow,united states,blue,semi soft,creamy,pale yellow,tangy,no

ML Data Preprocessing

In [16]:
cheese_data_df.shape

(103, 12)

In [17]:
cheese_data_df.cheese.value_counts()

feta                             4
brie                             2
parmesan                         2
crescenza                        1
sun-dried tomato herb fromage    1
                                ..
classic cheddar                  1
hatch green chili havarti        1
caraway cheddar                  1
bosque blue                      1
orchard blue                     1
Name: cheese, Length: 98, dtype: int64

In [18]:
# seperate data into feature and target arrays
y = cheese_data_df["cheese"]
x = cheese_data_df.drop(columns="cheese")

In [20]:
# isolate the categorical columns to be onehotencoded 
categorical_cols = x.select_dtypes(include="object").columns.to_list()

In [21]:
# build preprocessing pipeline 
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, PowerTransformer

In [24]:
# Create a col_transformer object
col_transformer = ColumnTransformer(
    transformers=[
        ("log", PowerTransformer()),
        (
            "oh_encode",
            OneHotEncoder(sparse=False, handle_unknown="ignore"),
            categorical_cols,
        ),
    ]
)

In [25]:
# Combine into a final pipeline
pipeline = Pipeline(
    steps=[("preprocess", col_transformer), 
    ("base_model", RandomForestClassifier())]
)

In [31]:
# Encode the target manually to encode the positive class
y = y.map({"+": 1, "-": 0})

In [32]:
cheese_data_df.dropna()

,cheese,company,city,price,milk,country,origin,classification,texture,color,flavor,vegetarian
0,crescenza,mozzarella company,dallas,9.39,cow,italy,italian,fresh soft,creamy,white,sweet,yes
1,smoked scamorza,mozzarella company,dallas,15.59,cow,italy,pasta filata,semi soft,firm,white,smokey,no
2,smoked mozzarella,mozzarella company,dallas,10.79,cow,italy,mozzarella,semi soft,bouncy,white,smokey,yes
3,queso oaxaca,mozzarella company,dallas,11.99,cow,mexico,pasta filata,semi hard,bouncy,white,buttery,yes
4,queso fresco,mozzarella company,dallas,10.79,cow,mexico,cottage,fresh soft,crumbly,white,milky,yes
...,...,...,...,...,...,...,...,...,...,...,...,...
98,feta,brazos valley cheese,waco,15,cow,greece,feta,soft brined,crumbly,white,tangy,no
99,marinated feta,brazos valley cheese,waco,14,cow,greece,feta,soft brined,crumbly,white,herby,no
100,marinated labneh,brazos valley cheese,waco,14,cow,middle east,labneh,soft,creamy,white,herby,no
101,mountain maple brie,brazos valley cheese,waco,22.5,cow,united states,brie,soft,creamy,cream,sweet,no
102,orchard blue,brazos valley cheese,waco,16.5,cow,united states,blue,semi soft,creamy,pale yellow,tangy,no

In [34]:
from sklearn.model_selection import train_test_split

# Generate train/test sets
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=0, stratify=y
)

# Fit/score the pipeline
pipeline.fit(X_train, y_train)

print(f"RandomForest pipeline scored {pipeline.score(X_test, y_test).round(3)}")

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [30]:
cheese_data_df.

,cheese,company,city,price,milk,country,origin,classification,texture,color,flavor,vegetarian
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
98,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False
100,False,False,False,False,False,False,False,False,False,False,False,False
101,False,False,False,False,False,False,False,False,False,False,False,False
102,False,False,False,False,False,False,False,False,False,False,False,False